locals {
  # azure_firewall       = yamldecode(file("./cloud_catalog/azure_firewall.yml"))
  # storage_acc          = yamldecode(file("./cloud_catalog/storage_acc.yml"))
  # sql_managed_instance = yamldecode(file("./cloud_catalog/sql_managed_instance.yml"))
  # mysql                = yamldecode(file("./cloud_catalog/mysql.yml"))
  # mariadb              = yamldecode(file("./cloud_catalog/mariadb.yml"))
  # acr                  = yamldecode(file("./cloud_catalog/acr.yml"))
  # adf                  = yamldecode(file("./cloud_catalog/adf.yml"))
  # postgres_single_db   = yamldecode(file("./cloud_catalog/postgres_single_db.yml"))
  # mssql                = yamldecode(file("./cloud_catalog/mssql.yml"))
  # linux_vm_config      = yamldecode(file("./cloud_catalog/linux_vm_config.yml"))
  win_vm_config        = yamldecode(file("./cloud_catalog/win_vm_config.yml"))
  # windows_vmss         = yamldecode(file("./cloud_catalog/windows_vmss.yml"))
  # linux_vmss           = yamldecode(file("./cloud_catalog/linux_vmss.yml"))
  # cosmos_db            = yamldecode(file("./cloud_catalog/cosmos_db.yml"))
  # akv_config           = yamldecode(file("./cloud_catalog/akv_config.yml"))
  # aks_config           = yamldecode(file("./cloud_catalog/aks_config.yml"))
  # migrate_config       = yamldecode(file("./cloud_catalog/migrate.yml"))
}