aks_config:
     - name: "sbxaks"
       dns_prefix: "sbxaksdns"
       node_rg: "rg-p-prd-aksnode"
       aks_node_pool:
            pool1:
               os_type: "Linux"
               vm_size: "Standard_DS2_v2"
               enable_auto_scaling: true
               max_count: 3
               min_count: 1

 