vm_config:
  linux_vm_defaults:  # Required
    size                : Standard_D2as_v4
    image_publisher     : Canonical
    image_offer         : 0001-com-ubuntu-server-focal
    image_sku           : 20_04-lts-gen2
    image_version       : latest
    admin_username      : vmadmin
    admin_password      : random  # "random" for random value
    timezone            : New Zealand Standard Time
    storage_account_type: Premium_LRS
  list:
    - name          : web07    
      size          : standard_b2ms
      subnet        : controlled 
      os_disk_size  : 32
      os_hostname   : vm01                  # Required (CAF naming convention in this case makes the vm name length > 16 characters, therefore the need for shorter hostname requirement)
      image_publisher : Canonical
      image_offer     : 0001-com-ubuntu-server-focal
      image_sku       : 20_04-lts-gen2
      admin_username  : ops
      image_version   : latest  # Optional that overrides the default
      managed_disks :                       # Block is optional, but all parameters are required if block has items in it
        - name                : disk1
          disk_size_gb        : 64
          create_option       : Empty
          lun                 : 1
          caching             : ReadWrite
    - name          : web08    
      size          : standard_b2ms
      subnet        : controlled 
      os_disk_size  : 32
      os_hostname   : vm02                  # Required (CAF naming convention in this case makes the vm name length > 16 characters, therefore the need for shorter hostname requirement)
      image_publisher : Canonical
      image_offer     : 0001-com-ubuntu-server-focal
      image_sku       : 20_04-lts-gen2
      admin_username  : ops
      image_version   : latest  # Optional that overrides the default
      managed_disks :                       # Block is optional, but all parameters are required if block has items in it
        - name                : disk2
          disk_size_gb        : 64
          create_option       : Empty
          lun                 : 1
          caching             : ReadWrite
    - name          : web09    
      size          : standard_b2ms
      subnet        : controlled 
      os_disk_size  : 32
      os_hostname   : vm03                  # Required (CAF naming convention in this case makes the vm name length > 16 characters, therefore the need for shorter hostname requirement)
      image_publisher : Canonical
      image_offer     : 0001-com-ubuntu-server-focal
      image_sku       : 20_04-lts-gen2
      admin_username  : ops
      image_version   : latest  # Optional that overrides the default
      managed_disks :                       # Block is optional, but all parameters are required if block has items in it
        - name                : disk3
          disk_size_gb        : 64
          create_option       : Empty
          lun                 : 1
          caching             : ReadWrite